name: Build and Release with Maven

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install TagAPI manually
        run: |
          mkdir -p libs
          curl -L -o libs/TagAPI.jar https://ci.md-5.net/job/TagAPI/lastSuccessfulBuild/artifact/target/TagAPI.jar
          mvn install:install-file -Dfile=libs/TagAPI.jar -DgroupId=org.kitteh -DartifactId=tag -Dversion=1.0 -Dpackaging=jar
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 8

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Download BuildTools
        run: |
          mkdir buildtools
          cd buildtools
          curl -o BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar

      - name: Build Spigot 1.8.8 and install to local repo
        run: |
          cd buildtools
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          java -jar BuildTools.jar --rev 1.8.8
        env:
          MAVEN_OPTS: -Xmx2G

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Get build artifact name
        id: artifact_name
        run: |
          FILE=$(find target -name "*.jar" | head -n 1)
          echo "file=$FILE" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          name: "Build ${{ github.run_number }}"
          draft: false
          prerelease: false
          files: ${{ steps.artifact_name.outputs.file }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
